export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const POST_LOADING = "POST_LOADING";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";

//ADMIN SIDE
export const GET_UNAPPROVEDPROFILES = "GET_UNAPPROVEDPROFILES";
export const DELETE_DECLINEREGISTRATION = "DELETE_DECLINEREGISTRATION";
export const POST_APPROVEREGISTRATION = "POST_APPROVEREGISTRATION";
export const GET_CLIENTPROFILES = "GET_CLIENTPROFILES";
export const GET_PRO_PROFILES = "GET_PRO_PROFILES";
export const GET_CURRENTCLIENTPROFILE = "GET_CURRENTCLIENTPROFILE";
export const DELETE_CLIENTACCOUNT = "DELETE_CLIENTACCOUNT";
